FROM node:22.5.1-alpine AS builder

WORKDIR /frontend
COPY package.json .

RUN npm install 

COPY . .

RUN npm run build

# Bundle static assets with nginx
FROM nginx:1.21.0-alpine AS production

# Copy built assets from builder
COPY --from=builder /frontend/build /usr/share/nginx/html

# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]