version: "3"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: 'movie_project_backend'
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/backend

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: 'movie_project_frontend'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - "backend"
    stdin_open: true
    tty: true