FROM python:3.12.4-slim

WORKDIR /backend
COPY requirements.txt .

RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["gunicorn","--workers=2","-b","0.0.0.0:5000","app:app"]